# Generated by Django 4.1 on 2022-11-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_tasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
